administrator/urls.py
from django.urls import path

from administrator import views

app_name = 'administrator'
urlpatterns = [
    path('employee/list/', views.employee_list_card, name='employee_list'),
    path('employer/list/', views.employer_list_card, name='employer_list'),
    path('jobs/list/<status>', views.job_listing, name='jobs_list'),
    path('jobs/list/', views.job_listing, name='jobs_list'),
    path('employee/<str:pid>/', views.employee_details, name='employee_details'),
    path('employer/<str:pid>/', views.employer_details, name='employer_details'),
    path('job/<str:job_key>/', views.job_details, name='job_details'),
    path('job/applications/<str:job_key>/', views.job_applications, name='job_applications'),
    path('interviews/', views.interview_list, name='interviews'),
    path('interview/submitted/<str:uid>', views.interview_submissions, name='interview_submitted'),
    path('interview/preview/answers/<str:iid>/<str:uid>', views.view_employee_interview_answer,
         name='interview_answers'),
    path('interview/preview/question/<str:iid>/', views.interview_questions, name='interview_question'),
    path('dm/chat/', views.admin_chat, name='admin_dm_chat'),
    path('staff/register', views.add_staff, name='add_staff'),
    path('super/staff/register', views.add_super_staff, name='add_super_staff'),
    path('staff/login', views.staff_login, name='staff_login'),
    path('staff/logout', views.staff_logout, name='staff_logout'),
    path('', views.index, name='index'),
    path('req_login/', views.req_login, name='req_login'),
    path('download_pdf/', views.download_pdf, name='download_pdf'),
    path('preview/cv/<str:pid>', views.preview_cv, name='preview_cv'),
    path('support_messages/', views.support_messages, name='support_messages'),
    path('support_messages/<str:mid>', views.read_support_messages, name='read_support_messages'),
    path('employment_form/', views.employment_form, name='employment_form'),
    path('employment_requests/', views.employment_requests, name='employment_requests'),
    path('process_employment/<str:req_id>', views.process_employment, name='process_employment'),
    path('process_payroll/<str:req_id>', views.process_payroll, name='process_payroll'),
    path('employments/', views.employments, name='employments'),
    path('payrolls/', views.payroll_list, name='payrolls'),
    path('create_payroll/<str:job_id>/<str:uid>', views.create_payroll, name='create_payroll'),
    path('payroll/payment/<str:pay_id>', views.make_payroll_payment, name='make_payroll_payment'),
    path('payroll/history/<str:pay_id>', views.payroll_payments, name='payroll_payments'),
    path('staffs', views.staff_list, name='staff_list'),
    path('access_denied', views.access_denied, name='access_denied'),
    path('staff/<str:uid>', views.update_staff, name='update_staff'),
    path('toggle/support_messages/<str:mid>', views.toggle_support_message, name='toggle_support_message'),
    path('report', views.report, name='report'),
    path('report/print/<str:start_date>/<str:end_date>', views.print_report, name='print_report'),
    path('decline_job/<job_id>', views.decline_job, name='decline_job'),
    path('approve_job/<job_id>', views.approve_job, name='approve_job'),
    path('suspend_application/<aid>', views.suspend_application, name='suspend_application'),
    path('approve_application/<aid>', views.approve_application, name='approve_application'),
    path('suspend_interview/<iid>', views.suspend_interview, name='suspend_interview'),
    path('approve_interview/<iid>', views.approve_interview, name='approve_interview'),
    path('delete_answers/<iid>/<uid>', views.delete_answers, name='delete_answers'),
    path('suspend_user/<uid>', views.suspend_user, name='suspend_user'),
    path('approve_user/<uid>', views.approve_user, name='approve_user'),
    path('employment_update/<uid>', views.employment_update, name='employment_update'),
    path('payroll/update/<pid>', views.update_payroll, name='update_payroll'),
    path('add_note/<uid>', views.add_note, name='add_note'),
    path('delete_note/<account>/<nid>/<uid>', views.delete_note, name='delete_note'),
    path('payroll_histories', views.payroll_histories, name='payroll_histories'),

]

api/urls.py
from django.urls import path, include

from chat.views import get_chats_head
from .views import index, checkauth, add_work_experience, view_employeeprofile, \
    work_experience_details, view_work_experiences, add_skill, skill_details, view_skills, add_education, \
    education_details, view_educations, add_language, language_details, view_languages, add_availability, \
    availability_details, view_availabilitys, add_employee, add_employer, post_job, employee_details, check_tag, \
    display_picture, view_job, apply_job, job_application_view, change_password, get_my_job, CustomLogin, get_positions, \
    get_industries, get_posted_jobs, job_application_list, create_shortlist, fetch_jobs, \
    get_relative_job_tags, company_logo, get_notifications, cv_preview, search_jobs, profile_preview, get_nearest_job, \
    get_my_interview, get_hot_alert, profile_details, employer_details, like_job, dislike_job, \
    filter_jobs, set_update_notify, set_newsletter_notify, set_email_notify, set_login_notify, send_employment_request, \
    notification_settings, hot_jobs, send_direct_employment_request, delete_account, support_message, close_job, \
    planUpgrade, upload_cv

app_name = 'api'
urlpatterns = [
    path('checkserver/', index, name='checksever'),
    path('checkauth/', checkauth, name='checkauth'),
    path('addskill/', add_skill, name='addskill'),
    path('addworkexperince/', add_work_experience, name='addworkexperience'),
    path('viewworkexperiences/', view_work_experiences, name='viewworkexperiences'),
    path('viewskills/', view_skills, name='viewskills'),
    path('view_employeeprofile/', view_employeeprofile, name='view_employeeprofile'),
    path('workexperiencedetails/<pk>', work_experience_details, name='work_experience_details'),
    path('skilldetails/<pk>', skill_details, name='skill_details'),
    path('addeducation/', add_education, name='addeducation'),
    path('educationdetails/<pk>', education_details, name='education_details'),
    path('vieweducations/', view_educations, name='vieweducations'),
    path('addlanguage/', add_language, name='addlanguage'),
    path('languagedetails/<pk>', language_details, name='language_details'),
    path('viewlanguages/', view_languages, name='viewlanguages'),
    path('addavailability/', add_availability, name='addavailability'),
    path('availabilitydetails/<pk>', availability_details, name='availability_details'),
    path('viewavailabilities/', view_availabilitys, name='viewavalabilitys'),
    path('addemployee/', add_employee, name='addemployee'),
    path('employeedetails/', employee_details, name='employee_details'),
    path('employerdetails/', employer_details, name='employer_details'),
    path('profile_details/', profile_details, name='profile_details'),
    path('addemployer/', add_employer, name='addemployer'),
    path('checktags/', check_tag, name='checktags'),
    path('postjob/', post_job, name='postjob'),
    path('viewjob/<str:jobid>', view_job, name='viewjob'),
    path('view_job_application/<str:uid>', job_application_view, name='viewjobapplication'),
    path('applyjob/', apply_job, name='applyjob'),
    path('display_picture/', display_picture, name='display_picture'),
    path('change_password/', change_password, name='change_password'),
    path('get_my_job/', get_my_job, name='getmyjob'),
    path('auth/login/', CustomLogin.as_view()),
    path('get_positions/', get_positions),
    path('get_industries/', get_industries),
    path('get_posted_jobs/', get_posted_jobs),
    path('fetch_jobs/', fetch_jobs),
    path('hot_jobs/', hot_jobs),
    path('cv_preview/', cv_preview),
    path('profile_preview/', profile_preview),
    path('get_nearest_job/', get_nearest_job),
    path('search/', search_jobs),
    path('filter/', filter_jobs),
    # path('locate/', get_location),
    path('relative_job_tags/', get_relative_job_tags),
    path('company_logo/', company_logo),
    path('job_application_list/<str:jobid>', job_application_list),
    path('create_shortlist/<str:jobid>', create_shortlist),
    path('like/<str:jobid>', like_job),
    path('dislike/<str:jobid>', dislike_job),
    path('fetch_notifications/', get_notifications),
    path('get_my_interview/', get_my_interview),
    path('notification_settings/', notification_settings),
    path('get_hot_alert/', get_hot_alert),
    path('delete_account/', delete_account),
    path('support_message/', support_message),
    path('set_newsletter_notify/<str:action>', set_newsletter_notify),
    path('set_login_notify/<str:action>', set_login_notify),
    path('set_email_notify/<str:action>', set_email_notify),
    path('set_update_notify/<str:action>', set_update_notify),
    path('plan_upgrade/<str:uid>/<str:plan>/<str:trans_id>', planUpgrade),
    path('send_employment_request/<str:interview_id>', send_employment_request),
    path('direct_employment_request/<str:job_id>', send_direct_employment_request),
    path('upload_cv/', upload_cv, name='upload_cv'),
    path('close_job/<str:job_id>', close_job),
    path('', include('djoser.urls')),
    path('', include('djoser.urls.authtoken')),

]

workaapi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from api.views import ActivateUser, reset_password

app_name = 'workaapi'
urlpatterns = [
    path('super_admin/', admin.site.urls),
    path('admin/', include('administrator.urls')),
    path('', include('api.urls')),
    path('interview/', include('interview.urls')),
    path('utility/', include('utility.urls')),
    path('chat/', include('chat.urls')),
    path('activate/<str:uid>/<str:token>/', ActivateUser.as_view(), name="user-activate"),
    path('password/reset/confirm/<str:uid>/<str:token>/', reset_password, name='passwordresetpage')

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrator/models.py
from django.db import models

# Create your models here.
from api.models import Employer, JobsPost, Employee, Staff, User
from interview.models import EmploymentRequest


class Employment(models.Model):
    STATUS = [
        ['active', 'active'],
        ['cancelled', 'cancelled'],
        ['suspended', 'suspended'],
    ]
    req = models.ForeignKey(EmploymentRequest, on_delete=models.CASCADE, related_name='processed_employment')
    currency = models.CharField(max_length=4)
    salary = models.PositiveIntegerField()
    resumption = models.DateField()
    employees_email = models.TextField()
    job = models.ForeignKey(JobsPost, on_delete=models.CASCADE, related_name='employed_job')
    status = models.CharField(max_length=255, choices=STATUS, default='active')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['job', 'employees_email']


class Payroll(models.Model):
    JOB_STATUS = [
        ['active', 'active'],
        ['cancelled', 'cancelled'],
        ['suspended', 'suspended'],
    ]
    PAYMENT_STATUS = [
        ['active', 'active'],
        ['completed', 'completed'],
        ['suspended', 'suspended'],
    ]
    job = models.ForeignKey(JobsPost, on_delete=models.CASCADE, related_name='payroll_job')
    payment_key = models.CharField(max_length=16)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='employed')
    currency = models.CharField(max_length=4)
    salary = models.PositiveIntegerField()
    monthly_charge = models.PositiveIntegerField()
    resumption = models.DateField()
    resignation = models.DateField(null=True)
    payment = models.PositiveIntegerField()
    balance = models.PositiveIntegerField(default=0)
    job_status = models.CharField(max_length=200, choices=JOB_STATUS, default='active')
    payment_status = models.CharField(max_length=200, choices=PAYMENT_STATUS, default='active')
    created = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ['job', 'employee']


class PayrollHistory(models.Model):
    payroll = models.ForeignKey(Payroll, on_delete=models.CASCADE, related_name='payroll_history')
    amount = models.PositiveIntegerField()
    balance = models.PositiveIntegerField()
    transaction = models.CharField(max_length=255)
    payer = models.ForeignKey(Staff, on_delete=models.ForeignKey)
    created = models.DateTimeField(auto_now=True)


class AdminNote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='admin_notes')
    note = models.TextField()
    writer = models.ForeignKey(Staff, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)


class UserLogs(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_logs')
    note = models.TextField()
    created = models.DateTimeField()


class JobLogs(models.Model):
    LOG = [
        ['post', 'post'],
        ['interview', 'interview'],
        ['shortlist', 'shortlist'],
        ['close', 'close'],
        ['update', 'update'],
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='job_logs')
    log = models.CharField(max_length=200, choices=LOG)
    note = models.TextField()
    created = models.DateTimeField()


class AdminLog(models.Model):
    LOG = [
        ['post', 'post'],
        ['request', 'support'],
        ['support', 'support'],
        ['delete', 'delete'],
        ['upgrade', 'upgrade'],
        ['payment', 'payment'],
        ['joined', 'joined'],
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='admin_logs')
    log = models.CharField(max_length=200, choices=LOG)
    note = models.TextField()
    created = models.DateTimeField()

administrator/templates/administrator/employment-requests.html
{% extends "administrator/header.html" %}
{% load mytag %}
{% block content %}

 <!-- content @s -->
                <div class="nk-content ">
                    <div class="container-fluid">
                        <div class="nk-content-inner">
                            <div class="nk-content-body">
                                <div class="components-preview wide-md mx-auto">


                                    <div class="nk-block nk-block-lg">
                                        <div class="nk-block-head">
                                            <div class="nk-block-head-content">
                                                <h4 class="nk-block-title">Employment Requests</h4>

                                            </div>
                                        </div>
                                        <div class="card card-preview">
                                            <div class="card-inner">
                                                <table class="datatable-init nowrap nk-tb-list nk-tb-ulist" data-auto-responsive="false">
                                                    <thead>
                                                        <tr class="nk-tb-item nk-tb-head">

                                                            <th class="nk-tb-col"><span class="sub-text">Title</span></th>
                                                            <th class="nk-tb-col tb-col-lg"><span class="sub-text">Note</span></th>
                                                            <th class="nk-tb-col tb-col-lg"><span class="sub-text">Applicants</span></th>
                                                            <th class="nk-tb-col tb-col-md"><span class="sub-text">Date</span></th>
                                                            <th class="nk-tb-col tb-col-md"><span class="sub-text">Status</span></th>
                                                            <th class="nk-tb-col nk-tb-col-tools text-right">
                                                            </th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                    {% for each in employment_list %}
                                                    {% with emp=each|sort_employment_request %}
                                                        <tr class="nk-tb-item">
                                                            <td class="nk-tb-col">
                                                                <div class="user-card">
                                                                    <div class="user-info">
                                                                        <span class="tb-lead">{{emp.job.title}} <span class="dot dot-success d-md-none ml-1"></span></span>
                                                                        <span>{{emp.job.employer.company_name}}</span>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                            <td class="nk-tb-col tb-col-lg text-wrap">
                                                                <span class="tb-amount">{{each.note}}</span>
                                                            </td>

                                                            <td class="nk-tb-col tb-col-lg text-wrap" data-order="Email Verified - Kyc Unverified">
                                                                <ul class="list-status">
                                                                    {% for req in each.employees|get_req_employee %}
                                                                    <li><span class="badge badge-xs badge-dark mb-1">{{req.fullname}}</span></li>
                                                                    {% endfor %}

                                                                </ul>
                                                            </td>
                                                            <td class="nk-tb-col tb-col-md">
                                                                <span class="tb-status ">{{each.created}}</span>                                                            </td>
                                                            <td class="nk-tb-col tb-col-md">
                                                                {% if each.status == 'pending' %}
                                                                <span class="tb-status text-warning">{{each.status}}</span>
                                                                {% elif each.status == 'suspended' %}
                                                                <span class="tb-status text-danger">{{each.status}}</span>
                                                                {% else %}
                                                                <span class="tb-status text-success">{{each.status}}</span>
                                                                {% endif %}
                                                            </td>
                                                            <td class="nk-tb-col nk-tb-col-tools">
                                                                <ul class="nk-tb-actions gx-1">

                                                                    <li>
                                                                        <div class="drodown">
                                                                            <a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
                                                                            <div class="dropdown-menu dropdown-menu-right">
                                                                                <ul class="link-list-opt no-bdr">
                                                                                    <li><a href="{% url 'administrator:job_details' emp.job.job_key %}"><em class="icon ni ni-focus"></em><span>View Job</span></a></li>
                                                                                    {% if each.status != 'processed' %}
                                                                                    <li><a href="{% url 'administrator:process_employment' each.id %}"><em class="icon ni ni-repeat"></em><span>Process Employment</span></a></li>
                                                                                    {% endif %}
                                                                                    <li><a href="{% url 'administrator:employer_details' emp.job.employer.uid %}"><em class="icon ni ni-user"></em><span>View Employer</span></a></li>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </li>
                                                                </ul>
                                                            </td>
                                                        </tr><!-- .nk-tb-item  -->
                                                    {% endwith %}
                                                    {% endfor %}
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div><!-- .card-preview -->
                                    </div> <!-- nk-block -->
                                </div><!-- .components-preview -->
                            </div>
                        </div>
                    </div>
                </div>
                <!-- content @e -->
{% endblock content%}
  {% block script %}


                {% endblock script%}

administrator/templates/administrator/employments.html
{% extends "administrator/header.html" %}
{% load mytag %}
{% block content %}

 <!-- content @s -->
                <div class="nk-content ">
                    <div class="container-fluid">
                        <div class="nk-content-inner">
                            <div class="nk-content-body">
                                <div class="components-preview wide-md mx-auto">


                                    <div class="nk-block nk-block-lg">
                                        <div class="nk-block-head">
                                            <div class="nk-block-head-content">
                                                <h4 class="nk-block-title">Employments</h4>

                                            </div>
                                        </div>
                                        <div class="card card-preview">
                                            <div class="card-inner">
                                                <table class="datatable-init nowrap nk-tb-list nk-tb-ulist" data-auto-responsive="false">
                                                    <thead>
                                                        <tr class="nk-tb-item nk-tb-head">

                                                            <th class="nk-tb-col"><span class="sub-text">Title</span></th>
                                                            <th class="nk-tb-col tb-col-lg"><span class="sub-text">Note</span></th>
                                                            <th class="nk-tb-col tb-col-lg"><span class="sub-text">Applicants</span></th>
                                                            <th class="nk-tb-col tb-col-md"><span class="sub-text">Resumption Date</span></th>
                                                            <th class="nk-tb-col tb-col-md"><span class="sub-text">Date</span></th>
                                                            <th class="nk-tb-col tb-col-md"><span class="sub-text">Status</span></th>
                                                            <th class="nk-tb-col nk-tb-col-tools text-right">
                                                            </th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                    {% for each in items %}
                                                        <tr class="nk-tb-item">
                                                            <td class="nk-tb-col">
                                                                <div class="user-card">
                                                                    <div class="user-info">
                                                                        <span class="tb-lead">{{each.job.title}} <span class="dot dot-success d-md-none ml-1"></span></span>
                                                                        <span>{{each.job.employer.company_name}}</span>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                            <td class="nk-tb-col tb-col-lg text-wrap">
                                                                <span class="tb-amount"> {{each.currency}} {{each.salary}}</span>
                                                            </td>

                                                            <td class="nk-tb-col tb-col-lg text-wrap" data-order="Email Verified - Kyc Unverified">
                                                                <ul class="list-status">
                                                                    {% for req in each.employees_email|get_employees %}
                                                                    <li><span class="badge badge-xs badge-dark mb-1">{{req.fullname}}</span></li>
                                                                    {% endfor %}

                                                                </ul>
                                                            </td>
                                                            <td class="nk-tb-col tb-col-md">
                                                                <span class="tb-status ">{{each.resumption}}</span>
                                                            </td>
                                                            <td class="nk-tb-col tb-col-md">
                                                                <span class="tb-status ">{{each.created}}</span>
                                                            </td>
                                                            <td class="nk-tb-col tb-col-md">
                                                                {% if each.status == 'suspended' %}
                                                                <span class="tb-status text-warning">{{each.status}}</span>
                                                                {% elif each.status == 'cancelled' %}
                                                                <span class="tb-status text-danger">{{each.status}}</span>
                                                                {% else %}
                                                                <span class="tb-status text-success">{{each.status}}</span>
                                                                {% endif %}
                                                            </td>
                                                            <td class="nk-tb-col nk-tb-col-tools">
                                                                <ul class="nk-tb-actions gx-1">

                                                                    <li>
                                                                        <div class="drodown">
                                                                            <a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
                                                                            <div class="dropdown-menu dropdown-menu-right">
                                                                                <ul class="link-list-opt no-bdr">
                                                                                    <li><a href="{% url 'administrator:job_details' each.job.job_key %}"><em class="icon ni ni-focus"></em><span>View Job</span></a></li>
                                                                                    <li><a href="{% url 'administrator:process_payroll' each.id %}"><em class="icon ni ni-repeat"></em><span>Process Employment</span></a></li>
                                                                                    <li><a href="{% url 'administrator:employer_details' each.job.employer.uid %}"><em class="icon ni ni-user"></em><span>View Employer</span></a></li>
                                                                                    <li class="divider"></li>
                                                                                    <li><a href="{% url 'administrator:employment_update' each.id %}"><em class="icon ni ni-edit"></em><span>Update</span></a></li>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </li>
                                                                </ul>
                                                            </td>
                                                        </tr><!-- .nk-tb-item  -->
                                                    {% endfor %}
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div><!-- .card-preview -->
                                    </div> <!-- nk-block -->
                                </div><!-- .components-preview -->
                            </div>
                        </div>
                    </div>
                </div>
                <!-- content @e -->
{% endblock content%}
  {% block script %}


                {% endblock script%}